// Auto generated file, don't modify.

#ifndef __META_IRRLICHT_KEYCODES_H
#define __META_IRRLICHT_KEYCODES_H


#include "gmetaobjectlifemanager_irrlicht_ireferencecounted.h"
#include "cpgf/gmetadefine.h"
#include "cpgf/metadata/gmetadataconfig.h"
#include "cpgf/metadata/private/gmetadata_header.h"
#include "cpgf/gmetapolicy.h"


using namespace irr;


namespace meta_irrlicht { 


template <typename D>
void buildMetaClass_Global_keycodes(const cpgf::GMetaDataConfigFlags & config, D _d)
{
    (void)config; (void)_d; (void)_d;
    using namespace cpgf;
    
    _d.CPGF_MD_TEMPLATE _enum<EKEY_CODE>("EKEY_CODE")
        ._element("KEY_LBUTTON", irr::KEY_LBUTTON)
        ._element("KEY_RBUTTON", irr::KEY_RBUTTON)
        ._element("KEY_CANCEL", irr::KEY_CANCEL)
        ._element("KEY_MBUTTON", irr::KEY_MBUTTON)
        ._element("KEY_XBUTTON1", irr::KEY_XBUTTON1)
        ._element("KEY_XBUTTON2", irr::KEY_XBUTTON2)
        ._element("KEY_BACK", irr::KEY_BACK)
        ._element("KEY_TAB", irr::KEY_TAB)
        ._element("KEY_CLEAR", irr::KEY_CLEAR)
        ._element("KEY_RETURN", irr::KEY_RETURN)
        ._element("KEY_SHIFT", irr::KEY_SHIFT)
        ._element("KEY_CONTROL", irr::KEY_CONTROL)
        ._element("KEY_MENU", irr::KEY_MENU)
        ._element("KEY_PAUSE", irr::KEY_PAUSE)
        ._element("KEY_CAPITAL", irr::KEY_CAPITAL)
        ._element("KEY_KANA", irr::KEY_KANA)
        ._element("KEY_HANGUEL", irr::KEY_HANGUEL)
        ._element("KEY_HANGUL", irr::KEY_HANGUL)
        ._element("KEY_JUNJA", irr::KEY_JUNJA)
        ._element("KEY_FINAL", irr::KEY_FINAL)
        ._element("KEY_HANJA", irr::KEY_HANJA)
        ._element("KEY_KANJI", irr::KEY_KANJI)
        ._element("KEY_ESCAPE", irr::KEY_ESCAPE)
        ._element("KEY_CONVERT", irr::KEY_CONVERT)
        ._element("KEY_NONCONVERT", irr::KEY_NONCONVERT)
        ._element("KEY_ACCEPT", irr::KEY_ACCEPT)
        ._element("KEY_MODECHANGE", irr::KEY_MODECHANGE)
        ._element("KEY_SPACE", irr::KEY_SPACE)
        ._element("KEY_PRIOR", irr::KEY_PRIOR)
        ._element("KEY_NEXT", irr::KEY_NEXT)
        ._element("KEY_END", irr::KEY_END)
        ._element("KEY_HOME", irr::KEY_HOME)
        ._element("KEY_LEFT", irr::KEY_LEFT)
        ._element("KEY_UP", irr::KEY_UP)
        ._element("KEY_RIGHT", irr::KEY_RIGHT)
        ._element("KEY_DOWN", irr::KEY_DOWN)
        ._element("KEY_SELECT", irr::KEY_SELECT)
        ._element("KEY_PRINT", irr::KEY_PRINT)
        ._element("KEY_EXECUT", irr::KEY_EXECUT)
        ._element("KEY_SNAPSHOT", irr::KEY_SNAPSHOT)
        ._element("KEY_INSERT", irr::KEY_INSERT)
        ._element("KEY_DELETE", irr::KEY_DELETE)
        ._element("KEY_HELP", irr::KEY_HELP)
        ._element("KEY_KEY_0", irr::KEY_KEY_0)
        ._element("KEY_KEY_1", irr::KEY_KEY_1)
        ._element("KEY_KEY_2", irr::KEY_KEY_2)
        ._element("KEY_KEY_3", irr::KEY_KEY_3)
        ._element("KEY_KEY_4", irr::KEY_KEY_4)
        ._element("KEY_KEY_5", irr::KEY_KEY_5)
        ._element("KEY_KEY_6", irr::KEY_KEY_6)
        ._element("KEY_KEY_7", irr::KEY_KEY_7)
        ._element("KEY_KEY_8", irr::KEY_KEY_8)
        ._element("KEY_KEY_9", irr::KEY_KEY_9)
        ._element("KEY_KEY_A", irr::KEY_KEY_A)
        ._element("KEY_KEY_B", irr::KEY_KEY_B)
        ._element("KEY_KEY_C", irr::KEY_KEY_C)
        ._element("KEY_KEY_D", irr::KEY_KEY_D)
        ._element("KEY_KEY_E", irr::KEY_KEY_E)
        ._element("KEY_KEY_F", irr::KEY_KEY_F)
        ._element("KEY_KEY_G", irr::KEY_KEY_G)
        ._element("KEY_KEY_H", irr::KEY_KEY_H)
        ._element("KEY_KEY_I", irr::KEY_KEY_I)
        ._element("KEY_KEY_J", irr::KEY_KEY_J)
        ._element("KEY_KEY_K", irr::KEY_KEY_K)
        ._element("KEY_KEY_L", irr::KEY_KEY_L)
        ._element("KEY_KEY_M", irr::KEY_KEY_M)
        ._element("KEY_KEY_N", irr::KEY_KEY_N)
        ._element("KEY_KEY_O", irr::KEY_KEY_O)
        ._element("KEY_KEY_P", irr::KEY_KEY_P)
        ._element("KEY_KEY_Q", irr::KEY_KEY_Q)
        ._element("KEY_KEY_R", irr::KEY_KEY_R)
        ._element("KEY_KEY_S", irr::KEY_KEY_S)
        ._element("KEY_KEY_T", irr::KEY_KEY_T)
        ._element("KEY_KEY_U", irr::KEY_KEY_U)
        ._element("KEY_KEY_V", irr::KEY_KEY_V)
        ._element("KEY_KEY_W", irr::KEY_KEY_W)
        ._element("KEY_KEY_X", irr::KEY_KEY_X)
        ._element("KEY_KEY_Y", irr::KEY_KEY_Y)
        ._element("KEY_KEY_Z", irr::KEY_KEY_Z)
        ._element("KEY_LWIN", irr::KEY_LWIN)
        ._element("KEY_RWIN", irr::KEY_RWIN)
        ._element("KEY_APPS", irr::KEY_APPS)
        ._element("KEY_SLEEP", irr::KEY_SLEEP)
        ._element("KEY_NUMPAD0", irr::KEY_NUMPAD0)
        ._element("KEY_NUMPAD1", irr::KEY_NUMPAD1)
        ._element("KEY_NUMPAD2", irr::KEY_NUMPAD2)
        ._element("KEY_NUMPAD3", irr::KEY_NUMPAD3)
        ._element("KEY_NUMPAD4", irr::KEY_NUMPAD4)
        ._element("KEY_NUMPAD5", irr::KEY_NUMPAD5)
        ._element("KEY_NUMPAD6", irr::KEY_NUMPAD6)
        ._element("KEY_NUMPAD7", irr::KEY_NUMPAD7)
        ._element("KEY_NUMPAD8", irr::KEY_NUMPAD8)
        ._element("KEY_NUMPAD9", irr::KEY_NUMPAD9)
        ._element("KEY_MULTIPLY", irr::KEY_MULTIPLY)
        ._element("KEY_ADD", irr::KEY_ADD)
        ._element("KEY_SEPARATOR", irr::KEY_SEPARATOR)
        ._element("KEY_SUBTRACT", irr::KEY_SUBTRACT)
        ._element("KEY_DECIMAL", irr::KEY_DECIMAL)
        ._element("KEY_DIVIDE", irr::KEY_DIVIDE)
        ._element("KEY_F1", irr::KEY_F1)
        ._element("KEY_F2", irr::KEY_F2)
        ._element("KEY_F3", irr::KEY_F3)
        ._element("KEY_F4", irr::KEY_F4)
        ._element("KEY_F5", irr::KEY_F5)
        ._element("KEY_F6", irr::KEY_F6)
        ._element("KEY_F7", irr::KEY_F7)
        ._element("KEY_F8", irr::KEY_F8)
        ._element("KEY_F9", irr::KEY_F9)
        ._element("KEY_F10", irr::KEY_F10)
        ._element("KEY_F11", irr::KEY_F11)
        ._element("KEY_F12", irr::KEY_F12)
        ._element("KEY_F13", irr::KEY_F13)
        ._element("KEY_F14", irr::KEY_F14)
        ._element("KEY_F15", irr::KEY_F15)
        ._element("KEY_F16", irr::KEY_F16)
        ._element("KEY_F17", irr::KEY_F17)
        ._element("KEY_F18", irr::KEY_F18)
        ._element("KEY_F19", irr::KEY_F19)
        ._element("KEY_F20", irr::KEY_F20)
        ._element("KEY_F21", irr::KEY_F21)
        ._element("KEY_F22", irr::KEY_F22)
        ._element("KEY_F23", irr::KEY_F23)
        ._element("KEY_F24", irr::KEY_F24)
        ._element("KEY_NUMLOCK", irr::KEY_NUMLOCK)
        ._element("KEY_SCROLL", irr::KEY_SCROLL)
        ._element("KEY_LSHIFT", irr::KEY_LSHIFT)
        ._element("KEY_RSHIFT", irr::KEY_RSHIFT)
        ._element("KEY_LCONTROL", irr::KEY_LCONTROL)
        ._element("KEY_RCONTROL", irr::KEY_RCONTROL)
        ._element("KEY_LMENU", irr::KEY_LMENU)
        ._element("KEY_RMENU", irr::KEY_RMENU)
        ._element("KEY_OEM_1", irr::KEY_OEM_1)
        ._element("KEY_PLUS", irr::KEY_PLUS)
        ._element("KEY_COMMA", irr::KEY_COMMA)
        ._element("KEY_MINUS", irr::KEY_MINUS)
        ._element("KEY_PERIOD", irr::KEY_PERIOD)
        ._element("KEY_OEM_2", irr::KEY_OEM_2)
        ._element("KEY_OEM_3", irr::KEY_OEM_3)
        ._element("KEY_OEM_4", irr::KEY_OEM_4)
        ._element("KEY_OEM_5", irr::KEY_OEM_5)
        ._element("KEY_OEM_6", irr::KEY_OEM_6)
        ._element("KEY_OEM_7", irr::KEY_OEM_7)
        ._element("KEY_OEM_8", irr::KEY_OEM_8)
        ._element("KEY_OEM_AX", irr::KEY_OEM_AX)
        ._element("KEY_OEM_102", irr::KEY_OEM_102)
        ._element("KEY_ATTN", irr::KEY_ATTN)
        ._element("KEY_CRSEL", irr::KEY_CRSEL)
        ._element("KEY_EXSEL", irr::KEY_EXSEL)
        ._element("KEY_EREOF", irr::KEY_EREOF)
        ._element("KEY_PLAY", irr::KEY_PLAY)
        ._element("KEY_ZOOM", irr::KEY_ZOOM)
        ._element("KEY_PA1", irr::KEY_PA1)
        ._element("KEY_OEM_CLEAR", irr::KEY_OEM_CLEAR)
        ._element("KEY_KEY_CODES_COUNT", irr::KEY_KEY_CODES_COUNT)
    ;
}


} // namespace meta_irrlicht




#include "cpgf/metadata/private/gmetadata_footer.h"


#endif
