// Auto generated file, don't modify.

#ifndef __REGISTER_META_IRRLICHT_H
#define __REGISTER_META_IRRLICHT_H


#include "cpgf/gmetadefine.h"


using namespace cpgf;

namespace meta_irrlicht { 


GDefineMetaInfo createMetaClass_Aabbox3d_TemplateInstance_aabbox3d_f32();
GDefineMetaInfo createMetaClass_Array_TemplateInstance_array_ILightSceneNodePointer();
GDefineMetaInfo createMetaClass_Array_TemplateInstance_array_ISceneNodePointer();
GDefineMetaInfo createMetaClass_Array_TemplateInstance_array_S3DVertex();
GDefineMetaInfo createMetaClass_Array_TemplateInstance_array_S3DVertex2TCoords();
GDefineMetaInfo createMetaClass_Array_TemplateInstance_array_f32();
GDefineMetaInfo createMetaClass_Array_TemplateInstance_array_u16();
GDefineMetaInfo createMetaClass_Array_TemplateInstance_tQ3EntityList();
GDefineMetaInfo createMetaClass_CDynamicMeshBuffer();
GDefineMetaInfo createMetaClass_CIndexBuffer();
GDefineMetaInfo createMetaClass_CMatrix4_TemplateInstance_matrix4();
GDefineMetaInfo createMetaClass_CMeshBuffer_TemplateInstance_SMeshBuffer();
GDefineMetaInfo createMetaClass_CMeshBuffer_TemplateInstance_SMeshBufferLightMap();
GDefineMetaInfo createMetaClass_CMeshBuffer_TemplateInstance_SMeshBufferTangents();
GDefineMetaInfo createMetaClass_CVertexBuffer();
GDefineMetaInfo createMetaClass_Dimension2d_TemplateInstance_dimension2d_f32();
GDefineMetaInfo createMetaClass_Dimension2d_TemplateInstance_dimension2d_u32();
GDefineMetaInfo createMetaClass_Dimension2d_TemplateInstance_dimension2df();
GDefineMetaInfo createMetaClass_Dimension2d_TemplateInstance_dimension2di();
GDefineMetaInfo createMetaClass_Dimension2d_TemplateInstance_dimension2du();
GDefineMetaInfo createMetaClass_Global_coreutil();
GDefineMetaInfo createMetaClass_Global_driverchoice();
GDefineMetaInfo createMetaClass_Global_eattributes();
GDefineMetaInfo createMetaClass_Global_ecullingtypes();
GDefineMetaInfo createMetaClass_Global_edebugscenetypes();
GDefineMetaInfo createMetaClass_Global_edevicetypes();
GDefineMetaInfo createMetaClass_Global_edriverfeatures();
GDefineMetaInfo createMetaClass_Global_edrivertypes();
GDefineMetaInfo createMetaClass_Global_eguialignment();
GDefineMetaInfo createMetaClass_Global_eguielementtypes();
GDefineMetaInfo createMetaClass_Global_ehardwarebufferflags();
GDefineMetaInfo createMetaClass_Global_ematerialflags();
GDefineMetaInfo createMetaClass_Global_ematerialtypes();
GDefineMetaInfo createMetaClass_Global_emeshwriterenums();
GDefineMetaInfo createMetaClass_Global_emessageboxflags();
GDefineMetaInfo createMetaClass_Global_eprimitivetypes();
GDefineMetaInfo createMetaClass_Global_escenenodeanimatortypes();
GDefineMetaInfo createMetaClass_Global_escenenodetypes();
GDefineMetaInfo createMetaClass_Global_eshadertypes();
GDefineMetaInfo createMetaClass_Global_eterrainelements();
GDefineMetaInfo createMetaClass_Global_fast_atof();
GDefineMetaInfo createMetaClass_Global_heapsort();
GDefineMetaInfo createMetaClass_Global_ianimatedmesh();
GDefineMetaInfo createMetaClass_Global_ianimatedmeshmd2();
GDefineMetaInfo createMetaClass_Global_ianimatedmeshmd3();
GDefineMetaInfo createMetaClass_Global_ianimatedmeshscenenode();
GDefineMetaInfo createMetaClass_Global_iattributeexchangingobject();
GDefineMetaInfo createMetaClass_Global_ibonescenenode();
GDefineMetaInfo createMetaClass_Global_icolladameshwriter();
GDefineMetaInfo createMetaClass_Global_icursorcontrol();
GDefineMetaInfo createMetaClass_Global_ieventreceiver();
GDefineMetaInfo createMetaClass_Global_ifilearchive();
GDefineMetaInfo createMetaClass_Global_igpuprogrammingservices();
GDefineMetaInfo createMetaClass_Global_iguibutton();
GDefineMetaInfo createMetaClass_Global_iguicontextmenu();
GDefineMetaInfo createMetaClass_Global_iguifont();
GDefineMetaInfo createMetaClass_Global_iguilistbox();
GDefineMetaInfo createMetaClass_Global_iguiskin();
GDefineMetaInfo createMetaClass_Global_iguitable();
GDefineMetaInfo createMetaClass_Global_ilogger();
GDefineMetaInfo createMetaClass_Global_iparticleaffector();
GDefineMetaInfo createMetaClass_Global_iparticleemitter();
GDefineMetaInfo createMetaClass_Global_iq3shader();
GDefineMetaInfo createMetaClass_Global_ireadfile();
GDefineMetaInfo createMetaClass_Global_irrallocator();
GDefineMetaInfo createMetaClass_Global_irrcompileconfig();
GDefineMetaInfo createMetaClass_Global_irrlicht();
GDefineMetaInfo createMetaClass_Global_irrmath();
GDefineMetaInfo createMetaClass_Global_irrstring();
GDefineMetaInfo createMetaClass_Global_irrtypes();
GDefineMetaInfo createMetaClass_Global_irrxml();
GDefineMetaInfo createMetaClass_Global_iscenemanager();
GDefineMetaInfo createMetaClass_Global_iskinnedmesh();
GDefineMetaInfo createMetaClass_Global_itexture();
GDefineMetaInfo createMetaClass_Global_ivideodriver();
GDefineMetaInfo createMetaClass_Global_iwritefile();
GDefineMetaInfo createMetaClass_Global_keycodes();
GDefineMetaInfo createMetaClass_Global_matrix4();
GDefineMetaInfo createMetaClass_Global_plane3d();
GDefineMetaInfo createMetaClass_Global_position2d();
GDefineMetaInfo createMetaClass_Global_quaternion();
GDefineMetaInfo createMetaClass_Global_s3dvertex();
GDefineMetaInfo createMetaClass_Global_sceneparameters();
GDefineMetaInfo createMetaClass_Global_scolor();
GDefineMetaInfo createMetaClass_Global_skeymap();
GDefineMetaInfo createMetaClass_Global_slight();
GDefineMetaInfo createMetaClass_Global_smaterial();
GDefineMetaInfo createMetaClass_Global_smateriallayer();
GDefineMetaInfo createMetaClass_Global_svertexindex();
GDefineMetaInfo createMetaClass_Global_vector2d();
GDefineMetaInfo createMetaClass_Global_vector3d();
GDefineMetaInfo createMetaClass_IAnimatedMesh();
GDefineMetaInfo createMetaClass_IAnimatedMeshMD2();
GDefineMetaInfo createMetaClass_IAnimatedMeshMD3();
GDefineMetaInfo createMetaClass_IAnimatedMeshSceneNode();
GDefineMetaInfo createMetaClass_IAnimationEndCallBack();
GDefineMetaInfo createMetaClass_IArchiveLoader();
GDefineMetaInfo createMetaClass_IAttributeExchangingObject();
GDefineMetaInfo createMetaClass_IAttributes();
GDefineMetaInfo createMetaClass_IBillboardSceneNode();
GDefineMetaInfo createMetaClass_IBillboardTextSceneNode();
GDefineMetaInfo createMetaClass_IBoneSceneNode();
GDefineMetaInfo createMetaClass_ICameraSceneNode();
GDefineMetaInfo createMetaClass_IColladaMeshWriter();
GDefineMetaInfo createMetaClass_IColladaMeshWriterNames();
GDefineMetaInfo createMetaClass_IColladaMeshWriterProperties();
GDefineMetaInfo createMetaClass_ICollisionCallback();
GDefineMetaInfo createMetaClass_ICursorControl();
GDefineMetaInfo createMetaClass_IDummyTransformationSceneNode();
GDefineMetaInfo createMetaClass_IDynamicMeshBuffer();
GDefineMetaInfo createMetaClass_IEventReceiver();
GDefineMetaInfo createMetaClass_IFileArchive();
GDefineMetaInfo createMetaClass_IFileList();
GDefineMetaInfo createMetaClass_IFileReadCallBack();
GDefineMetaInfo createMetaClass_IFileSystem();
GDefineMetaInfo createMetaClass_IGPUProgrammingServices();
GDefineMetaInfo createMetaClass_IGUIButton();
GDefineMetaInfo createMetaClass_IGUICheckBox();
GDefineMetaInfo createMetaClass_IGUIColorSelectDialog();
GDefineMetaInfo createMetaClass_IGUIComboBox();
GDefineMetaInfo createMetaClass_IGUIContextMenu();
GDefineMetaInfo createMetaClass_IGUIEditBox();
GDefineMetaInfo createMetaClass_IGUIElement();
GDefineMetaInfo createMetaClass_IGUIElementFactory();
GDefineMetaInfo createMetaClass_IGUIEnvironment();
GDefineMetaInfo createMetaClass_IGUIFileOpenDialog();
GDefineMetaInfo createMetaClass_IGUIFont();
GDefineMetaInfo createMetaClass_IGUIFontBitmap();
GDefineMetaInfo createMetaClass_IGUIImage();
GDefineMetaInfo createMetaClass_IGUIImageList();
GDefineMetaInfo createMetaClass_IGUIInOutFader();
GDefineMetaInfo createMetaClass_IGUIListBox();
GDefineMetaInfo createMetaClass_IGUIMeshViewer();
GDefineMetaInfo createMetaClass_IGUIScrollBar();
GDefineMetaInfo createMetaClass_IGUISkin();
GDefineMetaInfo createMetaClass_IGUISpinBox();
GDefineMetaInfo createMetaClass_IGUISpriteBank();
GDefineMetaInfo createMetaClass_IGUIStaticText();
GDefineMetaInfo createMetaClass_IGUITab();
GDefineMetaInfo createMetaClass_IGUITabControl();
GDefineMetaInfo createMetaClass_IGUITable();
GDefineMetaInfo createMetaClass_IGUIToolBar();
GDefineMetaInfo createMetaClass_IGUITreeView();
GDefineMetaInfo createMetaClass_IGUITreeViewNode();
GDefineMetaInfo createMetaClass_IGUIWindow();
GDefineMetaInfo createMetaClass_IGeometryCreator();
GDefineMetaInfo createMetaClass_IImage();
GDefineMetaInfo createMetaClass_IImageLoader();
GDefineMetaInfo createMetaClass_IImageWriter();
GDefineMetaInfo createMetaClass_IIndexBuffer();
GDefineMetaInfo createMetaClass_IIrrXMLReader_TemplateInstance_IXMLReader();
GDefineMetaInfo createMetaClass_IIrrXMLReader_TemplateInstance_IXMLReaderUTF8();
GDefineMetaInfo createMetaClass_ILightManager();
GDefineMetaInfo createMetaClass_ILightSceneNode();
GDefineMetaInfo createMetaClass_ILogger();
GDefineMetaInfo createMetaClass_IMaterialRenderer();
GDefineMetaInfo createMetaClass_IMaterialRendererServices();
GDefineMetaInfo createMetaClass_IMesh();
GDefineMetaInfo createMetaClass_IMeshBuffer();
GDefineMetaInfo createMetaClass_IMeshCache();
GDefineMetaInfo createMetaClass_IMeshLoader();
GDefineMetaInfo createMetaClass_IMeshManipulator();
GDefineMetaInfo createMetaClass_IMeshSceneNode();
GDefineMetaInfo createMetaClass_IMeshWriter();
GDefineMetaInfo createMetaClass_IMetaTriangleSelector();
GDefineMetaInfo createMetaClass_IOSOperator();
GDefineMetaInfo createMetaClass_IParticleAffector();
GDefineMetaInfo createMetaClass_IParticleAnimatedMeshSceneNodeEmitter();
GDefineMetaInfo createMetaClass_IParticleAttractionAffector();
GDefineMetaInfo createMetaClass_IParticleBoxEmitter();
GDefineMetaInfo createMetaClass_IParticleCylinderEmitter();
GDefineMetaInfo createMetaClass_IParticleEmitter();
GDefineMetaInfo createMetaClass_IParticleFadeOutAffector();
GDefineMetaInfo createMetaClass_IParticleGravityAffector();
GDefineMetaInfo createMetaClass_IParticleMeshEmitter();
GDefineMetaInfo createMetaClass_IParticleRingEmitter();
GDefineMetaInfo createMetaClass_IParticleRotationAffector();
GDefineMetaInfo createMetaClass_IParticleSphereEmitter();
GDefineMetaInfo createMetaClass_IParticleSystemSceneNode();
GDefineMetaInfo createMetaClass_IQ3LevelMesh();
GDefineMetaInfo createMetaClass_IRandomizer();
GDefineMetaInfo createMetaClass_IReadFile();
GDefineMetaInfo createMetaClass_IReferenceCounted();
GDefineMetaInfo createMetaClass_IRenderTarget();
GDefineMetaInfo createMetaClass_ISceneCollisionManager();
GDefineMetaInfo createMetaClass_ISceneLoader();
GDefineMetaInfo createMetaClass_ISceneManager();
GDefineMetaInfo createMetaClass_ISceneNode();
GDefineMetaInfo createMetaClass_ISceneNodeAnimator();
GDefineMetaInfo createMetaClass_ISceneNodeAnimatorCameraFPS();
GDefineMetaInfo createMetaClass_ISceneNodeAnimatorCameraMaya();
GDefineMetaInfo createMetaClass_ISceneNodeAnimatorCollisionResponse();
GDefineMetaInfo createMetaClass_ISceneNodeAnimatorFactory();
GDefineMetaInfo createMetaClass_ISceneNodeFactory();
GDefineMetaInfo createMetaClass_ISceneUserDataSerializer();
GDefineMetaInfo createMetaClass_IShader();
GDefineMetaInfo createMetaClass_IShaderConstantSetCallBack();
GDefineMetaInfo createMetaClass_IShaderManager();
GDefineMetaInfo createMetaClass_IShadowVolumeSceneNode();
GDefineMetaInfo createMetaClass_ISkinnedMesh();
GDefineMetaInfo createMetaClass_ITerrainSceneNode();
GDefineMetaInfo createMetaClass_ITextSceneNode();
GDefineMetaInfo createMetaClass_ITexture();
GDefineMetaInfo createMetaClass_ITimer();
GDefineMetaInfo createMetaClass_ITriangleSelector();
GDefineMetaInfo createMetaClass_IVertexBuffer();
GDefineMetaInfo createMetaClass_IVertexManipulator();
GDefineMetaInfo createMetaClass_IVideoDriver();
GDefineMetaInfo createMetaClass_IVideoModeList();
GDefineMetaInfo createMetaClass_IVolumeLightSceneNode();
GDefineMetaInfo createMetaClass_IWriteFile();
GDefineMetaInfo createMetaClass_IXMLBase();
GDefineMetaInfo createMetaClass_IXMLWriter();
GDefineMetaInfo createMetaClass_IrrlichtDevice();
GDefineMetaInfo createMetaClass_Line3d_TemplateInstance_line3d_f32();
GDefineMetaInfo createMetaClass_Noiser();
GDefineMetaInfo createMetaClass_Plane3d_TemplateInstance_plane3df();
GDefineMetaInfo createMetaClass_Plane3d_TemplateInstance_plane3di();
GDefineMetaInfo createMetaClass_Q3LevelLoadParameter();
GDefineMetaInfo createMetaClass_Quaternion();
GDefineMetaInfo createMetaClass_Rect_TemplateInstance_rect_s32();
GDefineMetaInfo createMetaClass_S3DVertex();
GDefineMetaInfo createMetaClass_S3DVertex2TCoords();
GDefineMetaInfo createMetaClass_S3DVertexTangents();
GDefineMetaInfo createMetaClass_SAnimatedMesh();
GDefineMetaInfo createMetaClass_SAttributeReadWriteOptions();
GDefineMetaInfo createMetaClass_SBlendFunc();
GDefineMetaInfo createMetaClass_SColor();
GDefineMetaInfo createMetaClass_SColorHSL();
GDefineMetaInfo createMetaClass_SColorf();
GDefineMetaInfo createMetaClass_SCursorSprite();
GDefineMetaInfo createMetaClass_SEvent();
GDefineMetaInfo createMetaClass_SGUISprite();
GDefineMetaInfo createMetaClass_SGUISpriteFrame();
GDefineMetaInfo createMetaClass_SIrrlichtCreationParameters();
GDefineMetaInfo createMetaClass_SJoystickInfo();
GDefineMetaInfo createMetaClass_SKeyMap();
GDefineMetaInfo createMetaClass_SLight();
GDefineMetaInfo createMetaClass_SMD3AnimationInfo();
GDefineMetaInfo createMetaClass_SMD3Face();
GDefineMetaInfo createMetaClass_SMD3Header();
GDefineMetaInfo createMetaClass_SMD3Mesh();
GDefineMetaInfo createMetaClass_SMD3MeshBuffer();
GDefineMetaInfo createMetaClass_SMD3MeshHeader();
GDefineMetaInfo createMetaClass_SMD3QuaternionTag();
GDefineMetaInfo createMetaClass_SMD3QuaternionTagList();
GDefineMetaInfo createMetaClass_SMD3TexCoord();
GDefineMetaInfo createMetaClass_SMD3Vertex();
GDefineMetaInfo createMetaClass_SMaterial();
GDefineMetaInfo createMetaClass_SMaterialLayer();
GDefineMetaInfo createMetaClass_SMesh();
GDefineMetaInfo createMetaClass_SModifierFunction();
GDefineMetaInfo createMetaClass_SNamedPath();
GDefineMetaInfo createMetaClass_SOverrideMaterial();
GDefineMetaInfo createMetaClass_SParticle();
GDefineMetaInfo createMetaClass_SSharedMeshBuffer();
GDefineMetaInfo createMetaClass_SSkinMeshBuffer();
GDefineMetaInfo createMetaClass_SVarGroup();
GDefineMetaInfo createMetaClass_SVarGroupList();
GDefineMetaInfo createMetaClass_SVariable();
GDefineMetaInfo createMetaClass_SVertexColorBrightnessManipulator();
GDefineMetaInfo createMetaClass_SVertexColorContrastBrightnessManipulator();
GDefineMetaInfo createMetaClass_SVertexColorContrastManipulator();
GDefineMetaInfo createMetaClass_SVertexColorDesaturateToAverageManipulator();
GDefineMetaInfo createMetaClass_SVertexColorDesaturateToLightnessManipulator();
GDefineMetaInfo createMetaClass_SVertexColorDesaturateToLuminanceManipulator();
GDefineMetaInfo createMetaClass_SVertexColorGammaManipulator();
GDefineMetaInfo createMetaClass_SVertexColorInterpolateLinearManipulator();
GDefineMetaInfo createMetaClass_SVertexColorInterpolateQuadraticManipulator();
GDefineMetaInfo createMetaClass_SVertexColorInvertManipulator();
GDefineMetaInfo createMetaClass_SVertexColorScaleManipulator();
GDefineMetaInfo createMetaClass_SVertexColorSetAlphaManipulator();
GDefineMetaInfo createMetaClass_SVertexColorSetManipulator();
GDefineMetaInfo createMetaClass_SVertexColorThresholdManipulator();
GDefineMetaInfo createMetaClass_SVertexPositionScaleAlongNormalsManipulator();
GDefineMetaInfo createMetaClass_SVertexPositionScaleManipulator();
GDefineMetaInfo createMetaClass_SVertexPositionTransformManipulator();
GDefineMetaInfo createMetaClass_SVertexTCoordsScaleManipulator();
GDefineMetaInfo createMetaClass_SViewFrustum();
GDefineMetaInfo createMetaClass_Triangle3d_TemplateInstance_triangle3df();
GDefineMetaInfo createMetaClass_Triangle3d_TemplateInstance_triangle3di();
GDefineMetaInfo createMetaClass_Vector2d_TemplateInstance_position2d_f32();
GDefineMetaInfo createMetaClass_Vector2d_TemplateInstance_position2d_s32();
GDefineMetaInfo createMetaClass_Vector2d_TemplateInstance_position2df();
GDefineMetaInfo createMetaClass_Vector2d_TemplateInstance_position2di();
GDefineMetaInfo createMetaClass_Vector3d_TemplateInstance_vector3df();
GDefineMetaInfo createMetaClass_Vector3d_TemplateInstance_vector3di();


template <typename Meta>
void registerMain_irrlicht(Meta _d)
{
    _d._class(createMetaClass_Aabbox3d_TemplateInstance_aabbox3d_f32());
    _d._class(createMetaClass_Array_TemplateInstance_array_ILightSceneNodePointer());
    _d._class(createMetaClass_Array_TemplateInstance_array_ISceneNodePointer());
    _d._class(createMetaClass_Array_TemplateInstance_array_S3DVertex());
    _d._class(createMetaClass_Array_TemplateInstance_array_S3DVertex2TCoords());
    _d._class(createMetaClass_Array_TemplateInstance_array_f32());
    _d._class(createMetaClass_Array_TemplateInstance_array_u16());
    _d._class(createMetaClass_Array_TemplateInstance_tQ3EntityList());
    _d._class(createMetaClass_CDynamicMeshBuffer());
    _d._class(createMetaClass_CIndexBuffer());
    _d._class(createMetaClass_CMatrix4_TemplateInstance_matrix4());
    _d._class(createMetaClass_CMeshBuffer_TemplateInstance_SMeshBuffer());
    _d._class(createMetaClass_CMeshBuffer_TemplateInstance_SMeshBufferLightMap());
    _d._class(createMetaClass_CMeshBuffer_TemplateInstance_SMeshBufferTangents());
    _d._class(createMetaClass_CVertexBuffer());
    _d._class(createMetaClass_Dimension2d_TemplateInstance_dimension2d_f32());
    _d._class(createMetaClass_Dimension2d_TemplateInstance_dimension2d_u32());
    _d._class(createMetaClass_Dimension2d_TemplateInstance_dimension2df());
    _d._class(createMetaClass_Dimension2d_TemplateInstance_dimension2di());
    _d._class(createMetaClass_Dimension2d_TemplateInstance_dimension2du());
    _d._class(createMetaClass_Global_coreutil());
    _d._class(createMetaClass_Global_driverchoice());
    _d._class(createMetaClass_Global_eattributes());
    _d._class(createMetaClass_Global_ecullingtypes());
    _d._class(createMetaClass_Global_edebugscenetypes());
    _d._class(createMetaClass_Global_edevicetypes());
    _d._class(createMetaClass_Global_edriverfeatures());
    _d._class(createMetaClass_Global_edrivertypes());
    _d._class(createMetaClass_Global_eguialignment());
    _d._class(createMetaClass_Global_eguielementtypes());
    _d._class(createMetaClass_Global_ehardwarebufferflags());
    _d._class(createMetaClass_Global_ematerialflags());
    _d._class(createMetaClass_Global_ematerialtypes());
    _d._class(createMetaClass_Global_emeshwriterenums());
    _d._class(createMetaClass_Global_emessageboxflags());
    _d._class(createMetaClass_Global_eprimitivetypes());
    _d._class(createMetaClass_Global_escenenodeanimatortypes());
    _d._class(createMetaClass_Global_escenenodetypes());
    _d._class(createMetaClass_Global_eshadertypes());
    _d._class(createMetaClass_Global_eterrainelements());
    _d._class(createMetaClass_Global_fast_atof());
    _d._class(createMetaClass_Global_heapsort());
    _d._class(createMetaClass_Global_ianimatedmesh());
    _d._class(createMetaClass_Global_ianimatedmeshmd2());
    _d._class(createMetaClass_Global_ianimatedmeshmd3());
    _d._class(createMetaClass_Global_ianimatedmeshscenenode());
    _d._class(createMetaClass_Global_iattributeexchangingobject());
    _d._class(createMetaClass_Global_ibonescenenode());
    _d._class(createMetaClass_Global_icolladameshwriter());
    _d._class(createMetaClass_Global_icursorcontrol());
    _d._class(createMetaClass_Global_ieventreceiver());
    _d._class(createMetaClass_Global_ifilearchive());
    _d._class(createMetaClass_Global_igpuprogrammingservices());
    _d._class(createMetaClass_Global_iguibutton());
    _d._class(createMetaClass_Global_iguicontextmenu());
    _d._class(createMetaClass_Global_iguifont());
    _d._class(createMetaClass_Global_iguilistbox());
    _d._class(createMetaClass_Global_iguiskin());
    _d._class(createMetaClass_Global_iguitable());
    _d._class(createMetaClass_Global_ilogger());
    _d._class(createMetaClass_Global_iparticleaffector());
    _d._class(createMetaClass_Global_iparticleemitter());
    _d._class(createMetaClass_Global_iq3shader());
    _d._class(createMetaClass_Global_ireadfile());
    _d._class(createMetaClass_Global_irrallocator());
    _d._class(createMetaClass_Global_irrcompileconfig());
    _d._class(createMetaClass_Global_irrlicht());
    _d._class(createMetaClass_Global_irrmath());
    _d._class(createMetaClass_Global_irrstring());
    _d._class(createMetaClass_Global_irrtypes());
    _d._class(createMetaClass_Global_irrxml());
    _d._class(createMetaClass_Global_iscenemanager());
    _d._class(createMetaClass_Global_iskinnedmesh());
    _d._class(createMetaClass_Global_itexture());
    _d._class(createMetaClass_Global_ivideodriver());
    _d._class(createMetaClass_Global_iwritefile());
    _d._class(createMetaClass_Global_keycodes());
    _d._class(createMetaClass_Global_matrix4());
    _d._class(createMetaClass_Global_plane3d());
    _d._class(createMetaClass_Global_position2d());
    _d._class(createMetaClass_Global_quaternion());
    _d._class(createMetaClass_Global_s3dvertex());
    _d._class(createMetaClass_Global_sceneparameters());
    _d._class(createMetaClass_Global_scolor());
    _d._class(createMetaClass_Global_skeymap());
    _d._class(createMetaClass_Global_slight());
    _d._class(createMetaClass_Global_smaterial());
    _d._class(createMetaClass_Global_smateriallayer());
    _d._class(createMetaClass_Global_svertexindex());
    _d._class(createMetaClass_Global_vector2d());
    _d._class(createMetaClass_Global_vector3d());
    _d._class(createMetaClass_IAnimatedMesh());
    _d._class(createMetaClass_IAnimatedMeshMD2());
    _d._class(createMetaClass_IAnimatedMeshMD3());
    _d._class(createMetaClass_IAnimatedMeshSceneNode());
    _d._class(createMetaClass_IAnimationEndCallBack());
    _d._class(createMetaClass_IArchiveLoader());
    _d._class(createMetaClass_IAttributeExchangingObject());
    _d._class(createMetaClass_IAttributes());
    _d._class(createMetaClass_IBillboardSceneNode());
    _d._class(createMetaClass_IBillboardTextSceneNode());
    _d._class(createMetaClass_IBoneSceneNode());
    _d._class(createMetaClass_ICameraSceneNode());
    _d._class(createMetaClass_IColladaMeshWriter());
    _d._class(createMetaClass_IColladaMeshWriterNames());
    _d._class(createMetaClass_IColladaMeshWriterProperties());
    _d._class(createMetaClass_ICollisionCallback());
    _d._class(createMetaClass_ICursorControl());
    _d._class(createMetaClass_IDummyTransformationSceneNode());
    _d._class(createMetaClass_IDynamicMeshBuffer());
    _d._class(createMetaClass_IEventReceiver());
    _d._class(createMetaClass_IFileArchive());
    _d._class(createMetaClass_IFileList());
    _d._class(createMetaClass_IFileReadCallBack());
    _d._class(createMetaClass_IFileSystem());
    _d._class(createMetaClass_IGPUProgrammingServices());
    _d._class(createMetaClass_IGUIButton());
    _d._class(createMetaClass_IGUICheckBox());
    _d._class(createMetaClass_IGUIColorSelectDialog());
    _d._class(createMetaClass_IGUIComboBox());
    _d._class(createMetaClass_IGUIContextMenu());
    _d._class(createMetaClass_IGUIEditBox());
    _d._class(createMetaClass_IGUIElement());
    _d._class(createMetaClass_IGUIElementFactory());
    _d._class(createMetaClass_IGUIEnvironment());
    _d._class(createMetaClass_IGUIFileOpenDialog());
    _d._class(createMetaClass_IGUIFont());
    _d._class(createMetaClass_IGUIFontBitmap());
    _d._class(createMetaClass_IGUIImage());
    _d._class(createMetaClass_IGUIImageList());
    _d._class(createMetaClass_IGUIInOutFader());
    _d._class(createMetaClass_IGUIListBox());
    _d._class(createMetaClass_IGUIMeshViewer());
    _d._class(createMetaClass_IGUIScrollBar());
    _d._class(createMetaClass_IGUISkin());
    _d._class(createMetaClass_IGUISpinBox());
    _d._class(createMetaClass_IGUISpriteBank());
    _d._class(createMetaClass_IGUIStaticText());
    _d._class(createMetaClass_IGUITab());
    _d._class(createMetaClass_IGUITabControl());
    _d._class(createMetaClass_IGUITable());
    _d._class(createMetaClass_IGUIToolBar());
    _d._class(createMetaClass_IGUITreeView());
    _d._class(createMetaClass_IGUITreeViewNode());
    _d._class(createMetaClass_IGUIWindow());
    _d._class(createMetaClass_IGeometryCreator());
    _d._class(createMetaClass_IImage());
    _d._class(createMetaClass_IImageLoader());
    _d._class(createMetaClass_IImageWriter());
    _d._class(createMetaClass_IIndexBuffer());
    _d._class(createMetaClass_IIrrXMLReader_TemplateInstance_IXMLReader());
    _d._class(createMetaClass_IIrrXMLReader_TemplateInstance_IXMLReaderUTF8());
    _d._class(createMetaClass_ILightManager());
    _d._class(createMetaClass_ILightSceneNode());
    _d._class(createMetaClass_ILogger());
    _d._class(createMetaClass_IMaterialRenderer());
    _d._class(createMetaClass_IMaterialRendererServices());
    _d._class(createMetaClass_IMesh());
    _d._class(createMetaClass_IMeshBuffer());
    _d._class(createMetaClass_IMeshCache());
    _d._class(createMetaClass_IMeshLoader());
    _d._class(createMetaClass_IMeshManipulator());
    _d._class(createMetaClass_IMeshSceneNode());
    _d._class(createMetaClass_IMeshWriter());
    _d._class(createMetaClass_IMetaTriangleSelector());
    _d._class(createMetaClass_IOSOperator());
    _d._class(createMetaClass_IParticleAffector());
    _d._class(createMetaClass_IParticleAnimatedMeshSceneNodeEmitter());
    _d._class(createMetaClass_IParticleAttractionAffector());
    _d._class(createMetaClass_IParticleBoxEmitter());
    _d._class(createMetaClass_IParticleCylinderEmitter());
    _d._class(createMetaClass_IParticleEmitter());
    _d._class(createMetaClass_IParticleFadeOutAffector());
    _d._class(createMetaClass_IParticleGravityAffector());
    _d._class(createMetaClass_IParticleMeshEmitter());
    _d._class(createMetaClass_IParticleRingEmitter());
    _d._class(createMetaClass_IParticleRotationAffector());
    _d._class(createMetaClass_IParticleSphereEmitter());
    _d._class(createMetaClass_IParticleSystemSceneNode());
    _d._class(createMetaClass_IQ3LevelMesh());
    _d._class(createMetaClass_IRandomizer());
    _d._class(createMetaClass_IReadFile());
    _d._class(createMetaClass_IReferenceCounted());
    _d._class(createMetaClass_IRenderTarget());
    _d._class(createMetaClass_ISceneCollisionManager());
    _d._class(createMetaClass_ISceneLoader());
    _d._class(createMetaClass_ISceneManager());
    _d._class(createMetaClass_ISceneNode());
    _d._class(createMetaClass_ISceneNodeAnimator());
    _d._class(createMetaClass_ISceneNodeAnimatorCameraFPS());
    _d._class(createMetaClass_ISceneNodeAnimatorCameraMaya());
    _d._class(createMetaClass_ISceneNodeAnimatorCollisionResponse());
    _d._class(createMetaClass_ISceneNodeAnimatorFactory());
    _d._class(createMetaClass_ISceneNodeFactory());
    _d._class(createMetaClass_ISceneUserDataSerializer());
    _d._class(createMetaClass_IShader());
    _d._class(createMetaClass_IShaderConstantSetCallBack());
    _d._class(createMetaClass_IShaderManager());
    _d._class(createMetaClass_IShadowVolumeSceneNode());
    _d._class(createMetaClass_ISkinnedMesh());
    _d._class(createMetaClass_ITerrainSceneNode());
    _d._class(createMetaClass_ITextSceneNode());
    _d._class(createMetaClass_ITexture());
    _d._class(createMetaClass_ITimer());
    _d._class(createMetaClass_ITriangleSelector());
    _d._class(createMetaClass_IVertexBuffer());
    _d._class(createMetaClass_IVertexManipulator());
    _d._class(createMetaClass_IVideoDriver());
    _d._class(createMetaClass_IVideoModeList());
    _d._class(createMetaClass_IVolumeLightSceneNode());
    _d._class(createMetaClass_IWriteFile());
    _d._class(createMetaClass_IXMLBase());
    _d._class(createMetaClass_IXMLWriter());
    _d._class(createMetaClass_IrrlichtDevice());
    _d._class(createMetaClass_Line3d_TemplateInstance_line3d_f32());
    _d._class(createMetaClass_Noiser());
    _d._class(createMetaClass_Plane3d_TemplateInstance_plane3df());
    _d._class(createMetaClass_Plane3d_TemplateInstance_plane3di());
    _d._class(createMetaClass_Q3LevelLoadParameter());
    _d._class(createMetaClass_Quaternion());
    _d._class(createMetaClass_Rect_TemplateInstance_rect_s32());
    _d._class(createMetaClass_S3DVertex());
    _d._class(createMetaClass_S3DVertex2TCoords());
    _d._class(createMetaClass_S3DVertexTangents());
    _d._class(createMetaClass_SAnimatedMesh());
    _d._class(createMetaClass_SAttributeReadWriteOptions());
    _d._class(createMetaClass_SBlendFunc());
    _d._class(createMetaClass_SColor());
    _d._class(createMetaClass_SColorHSL());
    _d._class(createMetaClass_SColorf());
    _d._class(createMetaClass_SCursorSprite());
    _d._class(createMetaClass_SEvent());
    _d._class(createMetaClass_SGUISprite());
    _d._class(createMetaClass_SGUISpriteFrame());
    _d._class(createMetaClass_SIrrlichtCreationParameters());
    _d._class(createMetaClass_SJoystickInfo());
    _d._class(createMetaClass_SKeyMap());
    _d._class(createMetaClass_SLight());
    _d._class(createMetaClass_SMD3AnimationInfo());
    _d._class(createMetaClass_SMD3Face());
    _d._class(createMetaClass_SMD3Header());
    _d._class(createMetaClass_SMD3Mesh());
    _d._class(createMetaClass_SMD3MeshBuffer());
    _d._class(createMetaClass_SMD3MeshHeader());
    _d._class(createMetaClass_SMD3QuaternionTag());
    _d._class(createMetaClass_SMD3QuaternionTagList());
    _d._class(createMetaClass_SMD3TexCoord());
    _d._class(createMetaClass_SMD3Vertex());
    _d._class(createMetaClass_SMaterial());
    _d._class(createMetaClass_SMaterialLayer());
    _d._class(createMetaClass_SMesh());
    _d._class(createMetaClass_SModifierFunction());
    _d._class(createMetaClass_SNamedPath());
    _d._class(createMetaClass_SOverrideMaterial());
    _d._class(createMetaClass_SParticle());
    _d._class(createMetaClass_SSharedMeshBuffer());
    _d._class(createMetaClass_SSkinMeshBuffer());
    _d._class(createMetaClass_SVarGroup());
    _d._class(createMetaClass_SVarGroupList());
    _d._class(createMetaClass_SVariable());
    _d._class(createMetaClass_SVertexColorBrightnessManipulator());
    _d._class(createMetaClass_SVertexColorContrastBrightnessManipulator());
    _d._class(createMetaClass_SVertexColorContrastManipulator());
    _d._class(createMetaClass_SVertexColorDesaturateToAverageManipulator());
    _d._class(createMetaClass_SVertexColorDesaturateToLightnessManipulator());
    _d._class(createMetaClass_SVertexColorDesaturateToLuminanceManipulator());
    _d._class(createMetaClass_SVertexColorGammaManipulator());
    _d._class(createMetaClass_SVertexColorInterpolateLinearManipulator());
    _d._class(createMetaClass_SVertexColorInterpolateQuadraticManipulator());
    _d._class(createMetaClass_SVertexColorInvertManipulator());
    _d._class(createMetaClass_SVertexColorScaleManipulator());
    _d._class(createMetaClass_SVertexColorSetAlphaManipulator());
    _d._class(createMetaClass_SVertexColorSetManipulator());
    _d._class(createMetaClass_SVertexColorThresholdManipulator());
    _d._class(createMetaClass_SVertexPositionScaleAlongNormalsManipulator());
    _d._class(createMetaClass_SVertexPositionScaleManipulator());
    _d._class(createMetaClass_SVertexPositionTransformManipulator());
    _d._class(createMetaClass_SVertexTCoordsScaleManipulator());
    _d._class(createMetaClass_SViewFrustum());
    _d._class(createMetaClass_Triangle3d_TemplateInstance_triangle3df());
    _d._class(createMetaClass_Triangle3d_TemplateInstance_triangle3di());
    _d._class(createMetaClass_Vector2d_TemplateInstance_position2d_f32());
    _d._class(createMetaClass_Vector2d_TemplateInstance_position2d_s32());
    _d._class(createMetaClass_Vector2d_TemplateInstance_position2df());
    _d._class(createMetaClass_Vector2d_TemplateInstance_position2di());
    _d._class(createMetaClass_Vector3d_TemplateInstance_vector3df());
    _d._class(createMetaClass_Vector3d_TemplateInstance_vector3di());
}

} // namespace meta_irrlicht




#endif
